# Generated by Django 3.2.7 on 2021-10-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_overdraft', models.BooleanField()),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('is_sent', models.BooleanField()),
                ('donor_bank_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_bank_account_id', to='mainApp.bankaccount')),
                ('recipient_bank_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_bank_account_id', to='mainApp.bankaccount')),
            ],
        ),
    ]
